/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Aurora' at '3/01/17 17:49' with Gradle 3.2.1
 *
 * @author Aurora, @date 3/01/17 17:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main( String[] args )
    {
        System.out.println( "Hola Mundo!" );
    }
}
